### ISSUE TITLE
Can't build v1.0.0 tag with Roboshell v3.2

### ISSUE THREAD

**Issue by maksimorlovich** [Studio3T/robomongo#1387]
I followed instructions for building on Mac OS X on this page:
https://github.com/Studio3T/robomongo/blob/master/docs/BuildingRobomongo.md

And everything builds fine, except for robomongo itself. I keep seeing compiler errors:
[  0%] Automatic moc, uic and rcc for target robomongo
[  0%] Automatic moc, uic and rcc for target qjson
[  1%] Automatic moc, uic and rcc for target qscintilla
[ 10%] Built target libssh2
[ 10%] Built target qjson_automoc
[ 12%] Built target ssh
[ 16%] Built target qjson
[ 16%] Built target qscintilla_automoc
[ 16%] Built target ssh_test
[ 17%] Built target server
[ 18%] Building CXX object src/third-party/qscintilla/CMakeFiles/qscintilla.dir/sources/Qt4Qt5/Qsci/moc_qsciabstractapis.cpp.o
[ 18%] Building CXX object src/third-party/qscintilla/CMakeFiles/qscintilla.dir/sources/Qt4Qt5/Qsci/moc_qsciapis.cpp.o
[ 18%] Building CXX object src/third-party/qscintilla/CMakeFiles/qscintilla.dir/sources/Qt4Qt5/Qsci/moc_qsciscintilla.cpp.o
[ 20%] Building CXX object src/third-party/qscintilla/CMakeFiles/qscintilla.dir/sources/Qt4Qt5/qscilexer.cpp.o
[ 21%] Building CXX object src/third-party/qscintilla/CMakeFiles/qscintilla.dir/sources/Qt4Qt5/qsciabstractapis.cpp.o
[ 23%] Building CXX object src/third-party/qscintilla/CMakeFiles/qscintilla.dir/sources/Qt4Qt5/qscicommand.cpp.o
[ 23%] Building CXX object src/third-party/qscintilla/CMakeFiles/qscintilla.dir/sources/Qt4Qt5/qsciscintilla.cpp.o
[ 23%] Built target robomongo_automoc
[ 23%] Building CXX object src/third-party/qscintilla/CMakeFiles/qscintilla.dir/sources/Qt4Qt5/ListBoxQt.cpp.o
In file included from In file included from /Users/robouser/Projects/robomongo/robomongo/src/third-party/qscintilla/sources/Qt4Qt5/qsciabstractapis.cpp:26:
In file included from /Users/robouser/Projects/robomongo/robomongo/src/third-party/qscintilla/sources/Qt4Qt5/Qsci/qsciabstractapis.h:39:
/Users/robouser/Projects/robomongo/robomongo/build/release/src/third-party/qscintilla/sources/Qt4Qt5/Qsci/moc_qsciscintilla.cpp:9:
/Users/robouser/Projects/robomongo/robomongo/src/third-party/qscintilla/sources/Qt4Qt5/Qsci/qsciscintilla.h:2110:25: error: implicit instantiation of undefined template 'QPointer<QsciLexer>'
/Users/robouser/Projects/robomongo/robomongo/build/release/src/third-party/qscintilla/sources/Qt4Qt5/Qsci/../../../../../../../../src/third-party/qscintilla/sources/Qt4Qt5/Qsci/qsciscintilla.h:2110:25: error: implicit
      instantiation of undefined template 'QPointer<QsciLexer>'
    QPointer<QsciLexer> lex;
                        ^
/Users/robouser/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qmetatype.h:1339:1: note: template is declared here
QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER(QT_FORWARD_DECLARE_SHARED_POINTER_TYPES_ITER)
^
/Users/robouser/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qmetatype.h:215:7: note: expanded from macro 'QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER'
    F(QPointer)
      ^
    QPointer<QsciLexer> lex;
                        ^
/Users/robouser/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qmetatype.h:1339:1: note: template is declared here
QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER(QT_FORWARD_DECLARE_SHARED_POINTER_TYPES_ITER)
^
/Users/robouser/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qmetatype.h:215:7: note: expanded from macro 'QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER'
    F(QPointer)
      ^
In file included from /Users/robouser/Projects/robomongo/robomongo/src/third-party/qscintilla/sources/Qt4Qt5/qscicommand.cpp:31:
/Users/robouser/Projects/robomongo/robomongo/src/third-party/qscintilla/sources/Qt4Qt5/Qsci/qsciscintilla.h:2110:25: error: implicit instantiation of undefined template 'QPointer<QsciLexer>'
    QPointer<QsciLexer> lex;
                        ^
/Users/robouser/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qmetatype.h:1339:1: note: template is declared here
QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER(QT_FORWARD_DECLARE_SHARED_POINTER_TYPES_ITER)
^
/Users/robouser/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qmetatype.h:215:7: note: expanded from macro 'QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER'
    F(QPointer)
      ^
/Users/robouser/Projects/robomongo/robomongo/src/third-party/qscintilla/sources/Qt4Qt5/qscicommand.cpp:46:16: error: no matching member function for call to 'SendScintilla'
        qsCmd->SendScintilla(QsciScintillaBase::SCI_ASSIGNCMDKEY, scikey,
        ~~~~~~~^~~~~~~~~~~~~
/Users/robouser/Projects/robomongo/robomongo/src/third-party/qscintilla/sources/Qt4Qt5/Qsci/qsciscintillabase.h:3118:10: note: candidate function not viable: no known conversion from 'QsciScintilla' to
      'const QsciScintillaBase' for object argument
    long SendScintilla(unsigned int msg, unsigned long wParam = 0,
         ^
/Users/robouser/Projects/robomongo/robomongo/src/third-party/qscintilla/sources/Qt4Qt5/Qsci/qsciscintillabase.h:3147:10: note: candidate function not viable: no known conversion from 'QsciScintilla' to
      'const QsciScintillaBase' /Users/robouser/Projects/robomongo/robomongo/build/release/src/third-party/qscintilla/sources/Qt4Qt5/Qsci/moc_qsciscintilla.cppfor: 730object: 31argument: 
error: cannot initialize object parameter of type 'QsciScintillaBase' with an expression
    long SendScintilla(unsigned int msg, unsigned long wParam,      
of          ^type
 'QsciScintilla'
/Users/robouser/Projects/robomongo/robomongo/src/third-party/qscintilla/sources/Qt4Qt5/Qsci/qsciscintillabase.h:3122:10: note: candidate function not    return QsciScintillaBase::qt_metacast(_clname); 
viable:                               ^~~~~~~~~~~no
 known conversion from 'QsciScintilla' to
      'const QsciScintillaBase' for object argument
    long SendScintilla(unsigned int msg, unsigned long wParam,
         ^
/Users/robouser/Projects/robomongo/robomongo/src/third-party/qscintilla/sources/Qt4Qt5/Qsci/qsciscintillabase.h:3126:10: note: candidate function not viable: no known conversion from 'QsciScintilla' to
      'const QsciScintillaBase' for/Users/robouser/Projects/robomongo/robomongo/build/release/src/third-party/qscintilla/sources/Qt4Qt5/Qsci/moc_qsciscintilla.cpp :object735 :argument30:
 error: cannot initialize object parameter of type 'QsciScintillaBase' with an     long SendScintilla(unsigned int msg, unsigned long wParam,expression

               ^of
 type 'QsciScintilla'
/Users/robouser/Projects/robomongo/robomongo/src/third-party/qscintilla/sources/Qt4Qt5/Qsci/qsciscintillabase.h:3158:10: note: candidate function not     _id = QsciScintillaBase::qt_metacall(_c, _id, _a);viable:
 no known conversion from 'QsciScintilla' to
      'const QsciScintillaBase'                              ^~~~~~~~~~~for
 object argument
    long SendScintilla(unsigned int msg, unsigned long wParam,
         ^
/Users/robouser/Projects/robomongo/robomongo/src/third-party/qscintilla/sources/Qt4Qt5/Qsci/qsciscintillabase.h:3162:10: note: candidate function not viable: no known conversion from 'QsciScintilla' to
      'const QsciScintillaBase' for object argument
    long SendScintilla(unsigned int msg, unsigned long wParam,
         ^
/Users/robouser/Projects/robomongo/robomongo/src/third-party/qscintilla/sources/Qt4Qt5/Qsci/qsciscintillabase.h:3133:10: note: candidate function not viable: no known conversion from 'QsciScintilla' to
      'const QsciScintillaBase' for object argument
    long SendScintilla(unsigned int msg, const char *wParam,
         ^
/Users/robouser/Projects/robomongo/robomongo/src/third-party/qscintilla/sources/Qt4Qt5/Qsci/qsciscintillabase.h:3130:10: note: candidate function not viable: requires 2 arguments, but 3 were provided
    long SendScintilla(unsigned int msg, const char *lParam) const;
         ^
/Users/robouser/Projects/robomongo/robomongo/src/third-party/qscintilla/sources/Qt4Qt5/Qsci/qsciscintillabase.h:3137:10: note: candidate function not viable: requires 2 arguments, but 3 were provided
    long SendScintilla(unsigned int msg, long wParam) const;
         ^
/Users/robouser/Projects/robomongo/robomongo/src/third-party/qscintilla/sources/Qt4Qt5/Qsci/qsciscintillabase.h:3140:10: note: candidate function not viable: requires 2 arguments, but 3 were provided
    long SendScintilla(unsigned int msg, int wParam) const;
         ^
/Users/robouser/Projects/robomongo/robomongo/src/third-party/qscintilla/sources/Qt4Qt5/Qsci/qsciscintillabase.h:3151:10: note: candidate function not viable: requires 2 arguments, but 3 were provided
    long SendScintilla(unsigned int msg, const QColor &col) const;
         ^
/Users/robouser/Projects/robomongo/robomongo/src/third-party/qscintilla/sources/Qt4Qt5/Qsci/qsciscintillabase.h:3143:10: note: candidate function not viable: requires 4 arguments, but 3 were provided
    long SendScintilla(unsigned int msg, long cpMin, long cpMax,
         ^
/Users/robouser/Projects/robomongo/robomongo/src/third-party/qscintilla/sources/Qt4Qt5/Qsci/qsciscintillabase.h:3154:10: note: candidate function not viable: requires 6 arguments, but 3 were provided
    long SendScintilla(unsigned int msg, unsigned long wParam, QPainter *hdc,
         ^
/Users/robouser/Projects/robomongo/robomongo/src/third-party/qscintilla/sources/Qt4Qt5/qscicommand.cpp:52:16: error: no matching member function for call to 'SendScintilla'
        qsCmd->SendScintilla(QsciScintillaBase::SCI_ASSIGNCMDKEY, scialtkey,
        ~~~~~~~^~~~~~~~~~~~~

Have you seen this before? I'm not sure how to proceed from here. Thanks!

**Comment by simsekgokhan** [comment]
Hi @maksimorlovich , thanks for your interest in Robomongo.
Since we moved to MongoDB 3.4, lots of things changed. This page will be updated in a couple of days.

But to help you now, these will be the key changes, please use:
- openssl-1.0.1u (not openssl-1.0.1p)
- roboshell-v3.4 branch:
- use Robomongo tag 1.1.1

**Comment by appVuze** [comment]
Hi @simsekgokhan , thanks for your reply. I tried getting the components per your recommendation, but my build still fails w/ the same errors. What is the recommended version of Qt to use? I'm using Qt5.7 on Mac OS X 10.11.6.

**Comment by simsekgokhan** [comment]
Yes, Qt5.7 is correct, other important points are below:

```
    A modern and complete C++11 compiler. One of the following is required:
        VS2015 Update 2 or newer
        GCC 5.3.0
        Clang 3.4 (or Apple XCode 5.1.1 Clang) or newer
    Python 2.7
    SCons 2.3.5 or newer (for MSVC 2015 support)
```

**Comment by appVuze** [comment]
Strange. I was able to build this on an older Macbook with older XCode version, but my new Macbook Pro with XCode 8.2.1 produces the issue. I was also able to build on a Ubuntu 16.04 platform without any issues, this is either something in my setup, or perhaps latest clang compiler doesn't like something about the code. Stay tuned.

**Comment by simsekgokhan** [comment]
Hi @appVuze , yes clang version might be the problem. 
We try to use tools with versions as close as suggested by MongoDB.

My previous comment is also from this MongoDB page:
https://github.com/mongodb/mongo/wiki/Build-Mongodb-From-Source#dependencies--installation
Look for `"To build the master branch..."`

**Comment by simsekgokhan** [comment]
Please see the updated documents:
- [Build Robo 3T - Mac OS X and Linux](https://github.com/paralect/robomongo/blob/master/docs/BuildRobo3TOnMacAndLinux.md) 
- [Build Robo 3T - Windows](https://github.com/paralect/robomongo/blob/master/docs/BuildRobo3TOnWindows.md)

**Comment by appVuze** [comment]
Thanks, @simsekgokhan

I tried an experiment. I installed XCode 7.3.1 alongside 8.2.1 and if I choose 7.3.1 with xcode-select -s, Robomongo builds just fine. However, 8.2.1 fails to compile with the errors I listed in this bug report.

I am using robomongo-shell v3.4 with tags/v1.1.1 of robomongo. And just to clarify, the shell builds fine, it's the Robomongo itself that I'm having issue building.
